package plugin.test;

public enum PluginError {
	
	NO_ERROR,
	EXCEPTION,
	NULL_POINTER,
	NO_SUCH_FILE,
	NOT_A_DIRECTORY,
	IS_A_DIRECTORY,
	FILE_ALREADY_EXISTS,
	WRONG_CONTENT,
	INDEX_OUT_OF_BOUNDS,
	DIRECTORY_NOT_EMPTY,
	ARRAY_INDEX_OUT_OF_BOUNDS,
	HTTP_RESPONSE,

}
